# Generated by Django 5.2.7 on 2025-10-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "Nebulosa"),
                    ("GALÁXIA", "Galáxia"),
                    ("PLANETA", "Planeta"),
                    ("ESTRELA", "Estrela"),
                ],
                default=("NEBULOSA", "Nebulosa"),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="descricao",
            field=models.TextField(default=""),
        ),
    ]
